import type { Metadata } from "next";
import { Geist, Caveat } from "next/font/google";
import { Taskbar } from "@/components/Taskbar";
import { Cursor } from "@react95/core";
import { StickyNote } from "@/components/StickyNote";
import "./globals.css";
import '@react95/core/GlobalStyle';
import '@react95/core/themes/win95.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${caveat.variable} ${Cursor.Auto} bg-win95 antialiased`}
      >
        <main className="m-2 flex flex-col flex-wrap w-fit gap-2 h-[calc(100dvh-2.5rem)]">
          {modal}
          {children}
        </main>
        <StickyNote />
        <Taskbar />
      </body>
    </html>
  );
}
